### ISSUE TITLE
Is this compatible with Meteor 1.5?

### ISSUE THREAD

**Issue by j18ter** [xcv58/meteor-collectionapi#36]
With default settings I get an empty response from curl for GET and POST does not add anything to the collection. Configured as standAlone I get this error:

W20170621-17:15:29.545(-7)? (STDERR) TypeError: listener must be a function
W20170621-17:15:29.546(-7)? (STDERR)     at Server.addListener (events.js:197:11)
W20170621-17:15:29.547(-7)? (STDERR)     at new Server (_http_server.js:235:10)

**Comment by xcv58** [comment]
Hi @j18ter,

I haven't touched this package for a while. It may have breaking change(s) from Meteor 1.3.1 to 1.5.
